### ISSUE TITLE
Gateway option in the end of subnet?

### ISSUE THREAD

**Issue by zyxep** [ITJamie/netbox_gateways#4]
Hi,

We are planning new network and would love to set gateway to be the top of the subnet, e.g. .254
Could this be an option to add?

**Comment by ITJamie** [comment]
You can set the gateqay to be whatever ip you want in the subnet.

**Comment by zyxep** [comment]
![Screenshot 2023-04-03 at 8 40 10 PM](https://user-images.githubusercontent.com/1403731/229597999-4dc3b6d2-bb39-4084-8257-c32988508bdc.png)
How would I add one then?? since the option doesn't give me an option to add one.

**Comment by ITJamie** [comment]
Have you created the ip you want to be the gateway in that prefix?
If so select it, you may want to choose the correct vrf also

The gateway ip plugin creates relationships between prefixes and ips. The gateway and the prefix must exist before you can link them

**Comment by zyxep** [comment]
Ahhhhh that how it works :D now i get it.

I have not created it ofc.

**Comment by zyxep** [comment]
side question then.
I have this list of subnets, and I have created subnets in each `/16` all at the end of it, why wouldn't my `/23`'s catch the gateways?

![Screenshot 2023-04-03 at 9 03 44 PM](https://user-images.githubusercontent.com/1403731/229602701-530afaca-e79a-4e81-a0ef-d652701b4485.png)

**Comment by ITJamie** [comment]
Im not sure what issue you are seeinng. 

We have plenty of large subnets with ips assigned as gateways at the end of the subnet.

As long as the ip is assigned to the same vrf as the prefix it should show as an option in the dropdown list when you wish to link ips and prefixes. 

Then when viewing a prefix with an assigned gateway it will show on the prefix details page
